iptables: use flock() instead of abstract unix sockets
Abstract unix sockets cannot be used to synchronize several concurrent
instances of iptables since an unpriviledged process can create them and
prevent the legitimate iptables instance from running.

Use flock() and /run instead as suggested by Lennart Poettering.

Fixes: 93587a0 ("ip[6]tables: Add locking to prevent concurrent instances")
Reported-by: Lennart Poettering <lennart@poettering.net>
Cc: Phil Oester <kernel@linuxace.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

xshared: calm down compilation warning

 xshared.c: In function ‘xtables_lock’:
 xshared.c:255:3: warning: implicit declaration of function ‘flock’ [-Wimplicit-function-declaration]

 Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>